 homeDeal=[
    {
        img:'https://m.media-amazon.com/images/I/61KKcUHzXTL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/711pkCwAsIL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/91bSzPG0F3L._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/71-idQ966EL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/71tuBk9UgML._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/71DZEPZEFRL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/81WWuDV6tyL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/91Icme6zMyL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/61Ednx4od8L._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/910HqJed2uL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/811hoHfK-GL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/811hoHfK-GL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/81vCZmNmjHL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/81nQC9n2mwL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/81Lwduxlw2L._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/814pVqSpIRL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/81eKr+1jY2L._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/91C-06XEJvL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/710bxyzw8EL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/71ZvCzN6iXL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/61uNwSwVZiL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/A1hDL33zg5L._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/7134v0c8gFL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/51FKy0zckGL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
    {
        img:'https://m.media-amazon.com/images/I/61WAbj9s0WL._AC_SY200_.jpg',
        discount:'',
        dealOfTheDay:''
    },
]